return {

    --[[
        ==================================================================
          Server Runtime
    ]]
     ['Bags']              = {
        --// Template //--

        --[[
              {
                ['Baggage']   = Instance;
                ['CFrame']    = CFrame;
                ['ID']        = number;
                ['Spawntime'] = number;
                ['Distance']  = number;
                ['Deleting']  = boolean;
              }
        ]]
     };

     --[[
        ==================================================================
         Client Runtime
     ]]

     ['DEFAULT Interval']  = 1;
     ['MIN Interval']      = 1;
     ['MAX Interval']      = 5;

     ['Length']            = 50;
     ['Speed']             = 10;

};